version: '3.8'

# EUCAIM Platform Configuration
# This compose file is optimized for EUCAIM platform deployment
# with strict adherence to EUCAIM standards

services:
  raclahe:
    image: raclahe:3.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raclahe-eucaim
    
    # EUCAIM standard volume mounts
    volumes:
      # Datasets directory (read-only on EUCAIM platform)
      - ${DATASET_PATH:-./input}:/home/ds/datasets:ro
      
      # Persistent home directory (for outputs and user data)
      - ${PERSISTENT_HOME:-./output}:/home/ds/persistent-home
      
      # Shared folder (for collaboration between containers)
      - ${SHARED_FOLDER:-./shared}:/home/ds/persistent-shared-folder
    
    # Default environment - EUCAIM compliant paths
    environment:
      - INPUT_DIR=/home/ds/datasets
      - OUTPUT_DIR=/home/ds/persistent-home/output
      - WEIGHTS_PATH=/home/ds/BBOX_WEIGHTS/WHOLE GLAND/checkpoint_external.h5
    
    # Run as ds user (uid 1000, gid 1000) - EUCAIM requirement
    user: "1000:1000"
    
    # Working directory
    working_dir: /home/ds
    
    # Security options (EUCAIM platform requirements)
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (optional, for extra security)
    # read_only: true
    # tmpfs:
    #   - /tmp
    #   - /home/ds/.cache
    
    # Network mode (no internet access simulates EUCAIM environment)
    network_mode: none
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    
    # Restart policy
    restart: "no"  # Batch job - don't restart on failure

